Repository starschema/COVID-19-data, pull requests merged in 2020-03, with the labels that each got.

#40 Set up docs folder.
  README.md
  docs/.gitkeep
Labels: documentation

#43 Covidtracker.com dataset
  .github/workflows/airflow.yml
  notebooks/CT_US_COVID_TESTS.ipynb
Labels: enhancement

#45 ISO 3166-2 level for certain states
  notebooks/JHU_COVID-19.ipynb
Labels: enhancement

#58 Support multiple reporting date in WHO
  notebooks/WHO_SITUATION_REPORTS.ipynb
  requirements.txt
Labels: enhancement

#71 JHU_COVID-19 notebook updated to accommodate 0323 breaking change
  notebooks/JHU_COVID-19.ipynb
  requirements.txt
Labels: bug

#72 Updated pd version for airflow compatibility.
  notebooks/JHU_COVID-19.ipynb
  requirements.txt
Labels: bug

#81 Metadata table
  .github/workflows/airflow.yml
  notebooks/METADATA.ipynb
Labels: documentation, enhancement

#85 COVID Tracking: add hospitalized patients
  notebooks/CT_US_COVID_TESTS.ipynb
  notebooks/METADATA.ipynb
Labels: enhancement

#84 Exclude active and recovered after 22MAR2020
  notebooks/JHU_COVID-19.ipynb
Labels: bug

#89 Integrate county level data
  notebooks/JHU_COVID-19.ipynb
  notebooks/METADATA.ipynb
Labels: enhancement

#95 Fix #91: missing deltas over the changeover period
  notebooks/JHU_COVID-19.ipynb
Labels: bug

#99 Added table level entries to METADATA table.
  notebooks/METADATA.ipynb
Labels: documentation

#101 KFF_US_ICU_BEDS integration
  README.md
  docs/index.md
  notebooks/METADATA.ipynb
Labels: documentation

#107 Patched US deltas for first data point.
  notebooks/JHU_COVID-19.ipynb
Labels: bug

#110 Fixes lat/long misassignment.
  notebooks/HS_BULK_DATA.ipynb
Labels: bug

#112 Added NYT data to METADATA, README.md and docs/
  README.md
  docs/index.md
  notebooks/METADATA.ipynb
Labels: documentation

#119 Fixes renaming of some geographies.
  notebooks/JHU_COVID-19.ipynb
Labels: bug

#121 Fixed Cruise Ship and Myanmar/Burma naming.
  notebooks/JHU_COVID-19.ipynb
Labels: bug

#129 Fix #128: county name inconsistencies.
  notebooks/JHU_COVID-19.ipynb
Labels: bug

#126 HDX data meta and documentation
  README.md
  docs/index.md
  notebooks/HUM_RESTRICTIONS.ipynb
  notebooks/METADATA.ipynb
Labels: documentation

#109 Added basic JHU vs WHO DQ checker.
  dags/covid_etl_dag.py
  notebooks/DQ_CHECKS.ipynb
  requirements.txt
Labels: enhancement
