Repository starschema/COVID-19-data, pull requests merged in 2020-04, with the labels that each got.

#142 ACAPS data importer
  README.md
  docs/index.md
  notebooks/HDX_ACAPS.ipynb
  notebooks/METADATA.ipynb
  refresh_schedules.json
  requirements.txt
Labels: enhancement

#192 Integrated RKI_GER_COVID19_DASHBOARD to metadata and documentation.
  README.md
  docs/index.md
  notebooks/METADATA.ipynb
Labels: documentation

#215 New fields added to KFF data on state mitigations
  notebooks/JHU_COVID-19.ipynb
  notebooks/KFF_US.ipynb
  notebooks/METADATA.ipynb
Labels: enhancement

#216 created IHME notebook
  README.md
  docs/index.md
  notebooks/IHME_COVID_19.ipynb
  notebooks/METADATA.ipynb
Labels: enhancement

#219 ISO 3166-2 length in IHME metadata.
  notebooks/METADATA.ipynb
Labels: bug
